salmobase/blast/urls.py
from django.urls import path
from . import views

app_name = 'blast'

urlpatterns = [
    path('input', views.input, name='input'),
    path('result', views.result, name='result'),
]

salmobase/genes/urls.py
from django.urls import path
from . import views

app_name = 'genes'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:gene_id>', views.gene, name='gene'),
    path('<str:species>/<str:gene_name>', views.geneByName, name='geneByName'),
    path('search', views.search, name='search'),
    path('orthogroup', views.orthogroup, name='orthogroup'),
    path('synteny', views.synteny, name='synteny'),
]

salmobase/salmobase/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('genes/', include('genes.urls')),
    path('genomes/', include('genomes.urls')),
#    path('tools', views.tools, name='tools'),
    path('blast/', include('blast.urls')),
    path('jbrowse/', include('jbrowse.urls')),
#    path('resources/', views.resources, name= 'resources'),
    re_path('djga/', include('google_analytics.urls')),
    path('alignments/', include('alignments.urls')),
]

salmobase/genes/models.py
from django.db import models

class Genes(models.Model):
    id = models.BigIntegerField(primary_key=True) # Note: unique number for each row in database.
    species = models.TextField()
    ann = models.TextField()
    asm = models.TextField()
    seqname = models.TextField()
    start = models.BigIntegerField()
    end = models.BigIntegerField()
    strand = models.TextField()
    gene_id = models.TextField()
    version = models.BigIntegerField(blank=True, null=True) # Ensembl gene version
    gene_name = models.TextField(blank=True)
    biotype = models.TextField()
    description = models.TextField(blank=True)
    og = models.TextField(blank=True) # ortholog group
    position = models.BigIntegerField() # the Nth gene along chromosome
    class Meta:
        managed = False

# gene ID conversion between different annotations of same assembly
class Xref(models.Model):
    species = models.TextField()
    asm = models.TextField()
    ann = models.TextField()
    gene_id = models.TextField(primary_key=True)
    ann_other = models.TextField()
    gene_id_other = models.TextField()
    class Meta:
        managed = False

class Transcripts(models.Model):
    gff_id = models.TextField(primary_key=True)
    species = models.TextField()
    ann = models.TextField()
    asm = models.TextField()
    seqname = models.TextField()
    start = models.BigIntegerField()
    end = models.BigIntegerField()
    feature = models.TextField()
    gene_id = models.TextField(blank=True)
    transcript_id = models.TextField(blank=True)
    class Meta:
        managed = False

class OG(models.Model):
    gene_id = models.TextField(primary_key=True)
    og = models.TextField()
    spc = models.TextField()
    salmonid = models.TextField(blank=True, null=True)
    teleost = models.TextField(blank=True, null=True)
    class Meta:
        managed = False

class Genetrees(models.Model):
    og = models.TextField(primary_key=True)
    cdsTree = models.TextField()

    class Meta:
        managed = False

salmobase/genes/views.py
from django.shortcuts import get_list_or_404, render, get_object_or_404
from django.http import JsonResponse, Http404
from genes.models import Genes, OG, Genetrees, Xref
from genes.documents import GenesDocument
import re
from salmobase.species import getPrimaryAssembly, nameToSpc, getOrthologyByPrefix, getOrthoSpeciesMeta
from jbrowse.generateConfig import getAnnotationTrackIDs, miniDefaultSessionConfig
import operator
from functools import reduce
from elasticsearch_dsl.query import Q

def index(request):
    return render(request, 'genes/index.html')

# TODO: move these functions to other file
def getGeneIDtype(ann):
    if( ann == "EnsemblRapid"):
        return("Ensembl")
    else:
        return(ann)

def getGeneIDlink(ann, gene_id):
    if( ann == "NCBI"):
        return("https://www.ncbi.nlm.nih.gov/gene/"+gene_id)
    elif( ann == "Ensembl"):
        return("https://ensembl.org/id/"+gene_id)
    elif( ann == "EnsemblRapid"):
        return("https://rapid.ensembl.org/id/"+gene_id)
    else:
        return("")

# Prepare the context for the gene view
def getGeneContext(gene):
    context = {
        'gene': gene,
        'gene_id_type': getGeneIDtype(gene.ann),
        'gene_id_link': getGeneIDlink(gene.ann, gene.gene_id),
        'annotation_tracks': ",".join(getAnnotationTrackIDs(gene.asm)),
        'jbrowse_data': miniDefaultSessionConfig( 
            assembly = gene.asm,
            location = f'{gene.seqname}:{round(gene.start-(gene.end-gene.start)*0.25)}..{round(gene.end+(gene.end-gene.start)*0.25)}',
            annotation =  gene.ann,
        ),
        'xref': Xref.objects.filter(gene_id=gene.gene_id, asm=gene.asm, ann=gene.ann)
    }
    return context

# (Helper function) Deal with multiple hits for the gene view.
def thereCanOnlyBeOne(gene, assembly):
    if len(gene) > 1:
        # Do something if there are multiple genes

        # If gene is found in multiple assemblies, use primary assembly
        if( assembly == ''):
            # select the gene from primary assembly
            genePrimary = [x for x in gene if x.asm == getPrimaryAssembly(x.species)]
            # use primary assembly gene if there is one
            gene = genePrimary if len(genePrimary)>0 else gene
            # TODO: what if there are multiple non-primary assemblies?

        # TODO: Deal with multiple loci. E.g. select the first and 
        # produce a list of loci that can be selected from a dropdown.
    return gene[0]


def gene(request, gene_id):
    assembly = request.GET.get('assembly', '')
    if( assembly != '' ):
        gene = get_list_or_404(Genes.objects.filter(gene_id=gene_id, asm=assembly))
    else:
        gene = get_list_or_404(Genes.objects.filter(gene_id=gene_id))
    
    gene = thereCanOnlyBeOne(gene, assembly)
    context = getGeneContext(gene)

    return render(request, "genes/gene.html", context)

def geneByName(request, species, gene_name):
    assembly = request.GET.get('assembly', '')
    if( assembly != '' ):
        gene = get_list_or_404(Genes.objects.filter(gene_name=gene_name, asm=assembly))
    else:
        gene = get_list_or_404(Genes.objects.filter(gene_name=gene_name, species=species))
    
    # TODO: Deal with multiple annotations! I.e. select primary annotation
    
    gene = thereCanOnlyBeOne(gene, assembly)
    context = getGeneContext(gene)

    return render(request, "genes/gene.html", context)

def search(request):
    # elasticsearch-dsl docs:
    # https://elasticsearch-dsl.readthedocs.io/en/stable/api.html
    # https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/search_as_you_type.py
    q = request.GET.get('q', '')
    assembly = request.GET.get('assembly', '')
    if assembly != '':
        assembly = assembly.split(",")
    annotation = request.GET.get('annotation', '')
    if annotation != '':
        annotation = annotation.split(",")
    i_from = request.GET.get('from', 1)
    i_to = request.GET.get('to', 99)
    format = request.GET.get('format', 'html')

    s = GenesDocument.search()
    s = s.query("multi_match", query=q, type="bool_prefix",
        fields=['gene_id^100', 'gene_id._3gram', 'gene_name^10', 'gene_name._3gram', 'description', "description._3gram"])
    # Filter assembly
    if assembly != '':
        filters = [Q('match', asm = x) for x in assembly]
        s = s.filter(reduce(operator.ior, filters)) # asm1 OR asm2 OR ...
    # Filter annotation
    if annotation != '':
        filters = [Q('match', ann = x) for x in annotation]
        s = s.filter(reduce(operator.ior, filters))
    nhits = s.count()
    s = s.highlight_options(no_match_size=200, pre_tags='<mark>', post_tags='</mark>').highlight('gene_id', 'gene_name', 'description')
    hits = s[min(nhits,int(i_from)-1):min(nhits,int(i_to))]
    results = [{ 'source': hit.to_dict(), 'highlight': hit.meta.highlight.to_dict() } for hit in hits]
            
    context = { 
        'q': q,
        'filter': {'assembly': ",".join(assembly), 'annotation': ",".join(annotation)},
        'i_from' : i_from,
        'i_to' : i_to,
        'nhits' : nhits,
        'nshown' : len(results),
        'results':  results 
    }
    if format == 'JSON':
        return JsonResponse(context, safe=True)
    else:
        return render(request, 'genes/search.html', context)

def orthogroup(request):
    og = request.GET.get('og', None)
    genetree = get_object_or_404(Genetrees.objects.filter(og=og))
    # generate gene metadata dictionary with
    geneslist = list(Genes.objects.filter(og=genetree.og).values('gene_id', 'gene_name', 'species','asm'))
    genesMeta = {}
    for e in geneslist:
        # name equal the tip labels in tree
        tiplabel=e['gene_id'] + "_" + nameToSpc(e['species'])
        genesMeta[tiplabel] = {
            'gene_id': e['gene_id'],
            'displayName': f"{e['gene_name']} ({e['species']})",
            'url': f"id/{e['gene_id']}?assembly={e['asm']}"
        }
        
    # geneslist = [{**e, "label": e['gene_id']+"_"+nameToSpc(e['species'])} for  e in  geneslist]
    context = {
        'og': genetree.og,
        'genesMeta' : genesMeta,
        'cds_tree' : genetree.cdsTree
    }
    return JsonResponse(context, safe=True)

def synteny(request):
    '''
    Given an orthogroup ID (og) and target gene return the orthologs with neighboring genes
    '''
    # get request arguments
    og = request.GET.get('og', None)
    if( og is None ):
        raise Http404('Missing "og" parameter')  
    gene_id = request.GET.get('gene_id', None)
    if( og is None ):
        raise Http404('Missing gene_id parameter')  

    # identify which orthology dataset to use
    ortho = getOrthologyByPrefix(og)
    if( ortho is None ):
        raise Http404("orthogroup ID not recognized")  

    # get the species names (i.e. alias used in the OG table) and asm
    orthoMeta = getOrthoSpeciesMeta(ortho)
    availSpcs = [v["name"] for v in orthoMeta.values()]
    spc2asm = {v["name"]: v["asm"] for k,v in orthoMeta.items()}
    spc2species = {v["name"]: k for k,v in orthoMeta.items()}

    # get orthologs
    orthologs = list(OG.objects.filter(og=og, spc__in=availSpcs).values('gene_id', 'spc', 'og', 'teleost', 'salmonid'))

    # verify that target gene is among orthologs
    if not gene_id in [x["gene_id"] for x in orthologs]:
        raise Http404("gene_id not found in orthogroup")

    coord = [] # used to keep track of paralogs
    for o in orthologs:
        # Create an ortholog "id" {OG}.{teleost node}.{salmonid node}. This is
        # used to sort the orthologs by clade
        o['id'] = ''.join((o['og'], re.search('\..*', o['teleost']).group(), re.search('\..*', o['salmonid']).group()))
        
        # get position and chromosome of ortholog
        asm = spc2asm[o['spc']]
        gene_obj = get_list_or_404(Genes.objects.filter(gene_id=o['gene_id'], asm=asm))[0]
        
        coord = coord + [{'chromosome': gene_obj.seqname, 'position': gene_obj.position}]
        
        o['chromosome'] = gene_obj.seqname
        o['species'] = spc2species[o['spc']]
        
        # get the direction of the ortholog
        o['direction'] = 'forward' if gene_obj.strand == '+' else 'reverse'
        
        # get neighboring genes
        pos = gene_obj.position
        o['neighbours'] = list(Genes.objects.filter(asm=asm, seqname=gene_obj.seqname, position__lte=pos+10, position__gte=pos-10).values('position', 'gene_id', 'gene_name', 'description', 'strand', 'og'))
        
        for n in o['neighbours']:
            # store assembly for each gene so that we can link to it
            n['asm'] = asm
            # add chromosome and species to diplay as part of gene info
            n['chromosome'] = o['chromosome']
            n['species'] = o['species']
            # add display x position "idx" from 0 to 20 where the ortholog is 10. Flip order of neigbours
            n['idx'] = 10 + (n['position']-pos) * (-1 if o['direction'] == 'reverse' else 1)
            del n['position']
            # flip direction (strand) of each gene if ortholog direction is reversed
            if o['direction'] == 'reverse':
                n['strand'] = {'+':'-','-':'+'}[n['strand']]

    for o in orthologs:
        if o['gene_id'] == gene_id:
            target_gene_neighbours = o['neighbours']
    
    # define color classes [number from 1-21] for each OG in target gene neighbours
    i = 1; color_classes = {}
    for n in target_gene_neighbours:
        n['color_class'] = i
        if n['og'] != None:
            color_classes[n['og']] = i
        i += 1
    # apply color classes to all neighbours of all orthologs
    for o in orthologs:
        for n in o['neighbours']:
            if n['og'] in color_classes.keys():
                n['color_class'] = color_classes[n['og']]
            else:
                n['color_class'] = 0

    
    if (len(orthologs)>1): #check if there're tandem genes and keep only one
        remove_index = []
        for i in range(0,len(orthologs)-2):

salmobase/genes/templates/genes/index.html
{% extends 'salmobase/base.html' %}
{% load static %}

{% block content %}
<h2>Check out genes</h2>
<h3>Search for a gene above, or click these examples:</h3>
<ul>
    <li><a href="{% url 'genes:geneByName' 'AtlanticSalmon' 'elov1' %}"><h3>elov1</h3></a></li>
    <li><a href="{% url 'genes:geneByName' 'AtlanticSalmon' 'lars' %}"><h3>lars</h3></a></li>
</ul>
{% endblock content %}

salmobase/genes/templates/genes/search.html
{% extends 'salmobase/base.html' %}
{% load static %}

{% block head %}
<!-- <link rel='stylesheet' type='text/css' href="{% static 'genes/css/search.css' %}"></style> -->
{% endblock head %}

{% block content %}

<div class='container-flex p-4'>
    <!-- search result header -->
    <div class="text-center">
        {% if nshown != nhits  %}
        Showing hits {{i_from}}..{{i_to}} of 
        {% endif %}
        <span class="badge rounded-pill bg-success">{{nhits}}</span>
        <span class="align-middle"> hits for '<em>{{q}}</em>'</span>
    </div>
    <div class="text-center">
        {% if filter.assembly != '' %}
        in assembly: {{filter.assembly}}
        {% endif %}
        {% if  filter.annotation != '' %}
        annotation source: {{filter.annotation}}
        {% endif %}
    </div>
    <div class="text-center">
        <span id="prev"></span>
        <span id="next"></span>
    </div>

    <!-- search result table -->
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Species</th>
                <th scope="col">Assembly</th>
                <th scope="col">Annotation</th>
                <th scope="col">Gene ID</th>
                <th scope="col">Gene Name</th>
                <th scope="col">Description</th>
                <th scope="col">Locus</th>
            </tr>
          </thead>
          <tbody>
            {% for gene in results %}
            <tr data-href="{% url 'genes:gene' gene.source.gene_id %}?assembly={{gene.source.asm}}">
                <td>{{gene.source.species}}</td>
                <td>{{gene.source.asm}}</td>
                <td>{{gene.source.ann}}</td>
                <td>{{gene.highlight.gene_id|first|safe}}</td>
                <td>{{gene.highlight.gene_name|first|safe}}</td>
                <td>{{gene.highlight.description|first|safe}}</td>
                <td>{{gene.source.seqname}}:{{gene.source.start}}..{{gene.source.end}} {{gene.source.strand}}</td>
            <tr>
            {% endfor %}
          </tbody>
    </table>
</div>
{% endblock content %}

{% block scripts %}
<script>
    if( {{i_from}} > 1 ){
        let el = document.getElementById('prev')
        let link = document.createElement('a')
        link.innerHTML="prev"
        link.href="{% url 'genes:search' %}?q={{q}}"+
                  "&from=" + Math.max(1,{{i_from}} - 100) + 
                  "&to=" + Math.max(1,{{i_from}} - 1) +
                  "&assembly={{filter.assembly}}" + 
                  "&annotation={{filter.annotation}}"
        el.appendChild(link)
    }
    if( {{i_to}} < {{nhits}} ){
        let el = document.getElementById('next')
        let link = document.createElement( 'a')
        link.innerHTML="next"
        link.href="{% url 'genes:search' %}?q={{q}}"+
                  "&from=" + Math.min({{nhits}},{{i_to}} + 1) + 
                  "&to=" + Math.min({{nhits}},{{i_to}} + 100) +
                  "&assembly={{filter.assembly}}" + 
                  "&annotation={{filter.annotation}}"
        el.appendChild(link)
    }
    //  Make table rows clickable
    $(function(){
        $('.table tr[data-href]').each(function(){
            $(this).css('cursor','pointer').hover(
                function(){ 
                    $(this).addClass('active'); 
                },  
                function(){ 
                    $(this).removeClass('active'); 
                }).click( function(){ 
                    document.location = $(this).attr('data-href'); 
                }
            );
        });
    });
</script>
<!-- <script>
    function toggleHidden(id) {
        var x = document.getElementById(id);
        if (x.hidden == true) { x.hidden = false } else { x.hidden = true }
    }
</script> -->
{% endblock scripts %}