salmobase/blast/urls.py
from django.urls import path
from . import views

app_name = 'blast'

urlpatterns = [
    path('input', views.input, name='input'),
    path('result', views.result, name='result'),
]

salmobase/genes/urls.py
from django.urls import path
from . import views

app_name = 'genes'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:gene_id>', views.gene, name='gene'),
    path('<str:species>/<str:gene_name>', views.geneByName, name='geneByName'),
    path('search', views.search, name='search'),
    path('orthogroup', views.orthogroup, name='orthogroup'),
    path('synteny', views.synteny, name='synteny'),
]

salmobase/genomes/urls.py
from django.urls import path
from . import views

app_name = 'genomes'

urlpatterns = [
    path('<str:species>/<str:assembly>/overview', views.overview, name='overview'),
]

salmobase/jbrowse/urls.py
from django.urls import path
from . import views

app_name = 'jbrowse'

urlpatterns = [
    path('', views.index, name='index'),
    path('config.json', views.config_json),
]

salmobase/salmobase/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('genes/', include('genes.urls')),
    path('genomes/', include('genomes.urls')),
#    path('tools', views.tools, name='tools'),
    path('blast/', include('blast.urls')),
    path('jbrowse/', include('jbrowse.urls')),
#    path('resources/', views.resources, name= 'resources'),
    re_path('djga/', include('google_analytics.urls')),
    path('alignments/', include('alignments.urls')),
]

salmobase/salmobase/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'salmobase/home.html')

def tools(request):
    return render(request, 'salmobase/tools.html')

def resources(request):
    return render(request, 'salmobase/resources.html')

salmobase/salmobase/templates/salmobase/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Salmobase</title>
    <!-- CSS -->
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">       
    <!-- Bootstrap icons: https://icons.getbootstrap.com/ -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Title font -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
    <!-- Cookie consent -->
    <link href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" rel="stylesheet">
    <!-- Animations -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet">
    <!-- Local -->
    <link href="{% static 'salmobase/css/bootnavbar.css' %}" rel="stylesheet">
    <link href="{% static 'salmobase/css/autocomplete.css' %}" rel="stylesheet">

    {% block head %}
    {% endblock head %}
</head>

<body>
    <!-- Google analystics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id="+"{{google_analytics_id}}"></script>
	<script>
      window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());
	  gtag('config', '{{google_analytics_id}}'); 
	</script>

    <!-- Header -->
    {% include "salmobase/header.html" %}
    
    <!-- Content -->
    {% block content %}
    {% endblock content%}

    <!-- Scripts -->
    <script src="{% static 'salmobase/js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Search autocomplete -->
    <script src="{% static 'salmobase/js/autocomplete.js' %}"></script>
    <script>
        autocomplete(
            input = document.getElementById("autocomplete-input"), 
            output = document.getElementById("autocomplete-output"), 
            search_url = "{% url 'genes:search' %}", 
            click_url = "{% url 'genes:index' %}"
        )
    </script>
    <!-- cookies consent -->
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
        window.cookieconsent.initialise({
            palette: {
                popup: {background: "#fff"},
                button: {background: "#aa0000"},
            },
            theme: "classic",
            position: "bottom",
            content: {
                message: "To comply with the EU GDPR regulation (General Data Protection Regulation), we would like to inform you that salmobase uses cookies to ensure you get the best experience on our website.",
            },
            revokable:true,
            onStatusChange: function(status) {
                console.log(this.hasConsented() ? 'enable cookies' : 'disable cookies');
            },
            law: {
                regionalLaw: false,
            },
        });
    </script>
    <!-- cookies consent -->
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

salmobase/salmobase/templates/salmobase/header.html
{% load static  %}
{% url 'home' as home_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="main_navbar">
  <div class="container-fluid">
      <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Nav left -->
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarSupportedContent">
      <!-- Nav Links -->
      <ul class="navbar-nav me-auto">
        <!-- Genomes -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Genomes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for x,y in all_species.items %}
                <li class="nav-item dropdown">
                  <a class="dropdown-item dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                    {{ y.name_text }} 
                  </a>
                  <ul class="dropdown-menu">
                    {% for z in y.assemblies%}
                      <li><a class="dropdown-item" href="{% url 'genomes:overview' x z%}">{{z}}</a></li>
                    {% endfor %}  
                  </ul>  
                </li>
            {% endfor %}
          </ul>
        </li>
        <!-- Tools -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Tools
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'jbrowse:index' %}">JBrowse</a></li>
            <li><a class="dropdown-item" href="{% url 'blast:input' %}">BLAST</a></li>
            <li><a class="dropdown-item" href="https://v2.salmobase.org/SalMotifDB/">SalMotifDB</a></li>
          </ul>
        </li>
        <!-- Resources -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Resources
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!-- <li><h6 class="dropdown-header">Downloads</h6></li> -->
              <li><a class="dropdown-item" href="https://salmobase.org/datafiles/">Browse files</a></li>
              <!-- <li><hr class="dropdown-divider"></li> -->
              <!-- <li><h6 class="dropdown-header ">API</h6></li> -->
              <!-- <li><a class="dropdown-item disabled" href="#">Site API</a></li> -->
              <!-- <li><a class="dropdown-item disabled" href="#">R</a></li> -->
              <!-- <li><hr class="dropdown-divider"></li> -->
              <!-- <li><h6 class="dropdown-header ">Documentation</h6></li> -->
              <!-- <li><a class="dropdown-item disabled" href="#">Tutorials</a></li> -->
            </ul>
        </li>
        <!-- Help -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Help
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'home' %}#About">About</a></li>
            <li><a class="dropdown-item" href="{% url 'home' %}#Feedback">Feedback</a></li>
            <li><a class="dropdown-item" href="https://gitlab.com/elixir-nmbu/salmobase">Source code</a></li>
          </ul>
        </li>
        </ul>
      </div>
      <!-- Nav middle -->
      <div class="mx-auto order-0">
        <!-- Title -->
        {% if request.get_full_path != home_url %}
          <a class="navbar-brand mx-auto" style="font-family: 'Comfortaa', cursive;" href="{% url 'home' %}">Salmobase</a>
        {% endif %}
      </div>

      {% if request.get_full_path != home_url %}
      <!-- Nav right -->
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <!-- Search bar -->
        <div class="col-md-8 ms-auto">
          {% include "salmobase/searchbar.html" %}
        <div class="position-relative" >
          <div id="autocomplete-output" class="position-absolute top-0 end-0" style="z-index: 10000; overflow-y: auto; height: 600px;"></div>
        </div>
      </div>
      {% endif %}
  </div> <!-- container -->
</nav> <!-- Nav -->
  
<script src="{% static 'salmobase/js/bootnavbar.js' %}"></script>
<script>
  new bootnavbar();
  // (function () {
  // });
</script>
<script>
  document.addEventListener("DOMContentLoaded", function(){
    // make it as accordion for smaller screens
    if (window.innerWidth < 992) {
    
      // close all inner dropdowns when parent is closed
      document.querySelectorAll('.navbar .dropdown').forEach(function(everydropdown){
        everydropdown.addEventListener('hidden.bs.dropdown', function () {
          // after dropdown is hidden, then find all submenus
            this.querySelectorAll('.submenu').forEach(function(everysubmenu){
              // hide every submenu as well
              everysubmenu.style.display = 'none';
            });
        })
      });
    
      document.querySelectorAll('.dropdown-menu a').forEach(function(element){
        element.addEventListener('click', function (e) {
            let nextEl = this.nextElementSibling;
            if(nextEl && nextEl.classList.contains('submenu')) {	
              // prevent opening link if link needs to open dropdown
              e.preventDefault();
              if(nextEl.style.display == 'block'){
                nextEl.style.display = 'none';
              } else {
                nextEl.style.display = 'block';
              }
    
            }
        });
      })
    }
    // end if innerWidth
    }); 
    // DOMContentLoaded  end
  </script>

salmobase/salmobase/templates/salmobase/home.html
{% extends 'salmobase/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">

  <!-- Title and search -->
  <div class="px-4">
      <h1 class="display-1 mb-4 text-center" style="font-family: 'Comfortaa', cursive;">Salmobase</h1>
      <div class="alert alert-info col-md-3 mx-auto justify-content-center" role="alert">
        Updated 2023-04-11
        (<a href="#Update">What has changed</a>)
      </div>
      <!-- Search bar -->
      <div class="col-md-4 mx-auto justify-content-center">
        {% include "salmobase/searchbar.html" %}
      </div>
      <div class="col-md-8 mx-auto justify-content-center position-relative">
          <div id="autocomplete-output" class="w-100 position-absolute top-0 start-50 translate-middle-x" style="z-index: 1; overflow-y: auto; height: 500px;"></div>
      </div>
  </div>

  <!-- Overview image -->
  <div class="position-relative mb-4" style="top: -20px; z-index: -1;">
      <img src="{% static 'salmobase/img/overview.png' %}" class="img-fluid" alt="overview">
  </div>

  <div class="row mb-5">
    <div class="col-md-8 p-4">
        <h1 id="Update" class="mb-1" style="font-family: 'Comfortaa', cursive;">Updates</h1>
        <div class="border-start ps-3" style="text-align: justify; border-left: 10px solid #0072BC !important;">
          <p class="lead">
            <h3>Update 2023-04-11</h3>
            <ul class="list-unstyled">
              <li>"Genome browser" removed from menu. The genome browser can now be opened from the genome page by clicking on a chromosome or by select JBrowse from the tools menu.</li>
              <li>Link to download choromosomes.tsv on genome page.</li>
              <li>Added tracks:
                <ul>
                  <li>Comparative genome alignments for salmon and trout</li>
                  <li>Comparative ortholog/paralog tracks</li>
                </ul>
              </li>
            </ul>
            <h3>Update 2023-01-02:</h3>
            <ul class="list-unstyled">
              <li>Added assemblies:
                <ul>
                  <li>Atlantic salmon: Ssal_Brian_v1.0</li>
                  <li>Atlantic salmon: Ssal_ALTA</li>
                </ul>
              </li>
              <li>Gene page now shows link between Ensembl and NCBI annotation</li>
            </ul>
            <h3>Correction 2022-12-05:</h3>
            The assembly that was originally submitted as Arctic char (Salvelinus alpinus) has been corrected to Dolly Varden (Salvelinus malma). See <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0247083">this retraction notice</a>.
            <h3>November 2022 Update:</h3>
            <ul class="list-unstyled">
              <li>Added assemblies:
                <ul>
                  <li>Atlantic salmon: Ssal_v3.1</li>
                  <li>Rainbow trout: USDA_OmykA_1.1</li>
                  <li>Coho salmon: Okis_V2</li>
                </ul>
              </li>
              <li>Now includes both NCBI and Ensembl annotations when available.</li>
              <li>Support for multiple assemblies per species (I.e. old assemblies are still available).</li>
              <li>Added filter for gene search: Search selected species, assembly or annotation.</li>
              <li>New gene trees and ortholog groups for the new species based on Ensembl annotations.</li>
              <li>Chromosome alias: Now possible to load tracks with alternative sequence names. Valid sequence IDs are. refseq, genbank, Ensembl or “sequence name”. Aliases are also displayed when hovering the chromosome on the genome page.</li>
              <li>Gene page URL now uses geneIDs by default (NCBI gene ID or Ensembl gene ID). Gene annotations from earlier assemblies can be accessed by specifying the assembly with a parameter. E.g. https://salmobase.org/genes/id/100306804?assembly=ICSASG_v2</li>
            </ul>
        </div>

      <!-- About -->
        <h1 id="About" class="mb-1" style="font-family: 'Comfortaa', cursive;">About Salmobase</h1>
        <div class="border-start ps-3" style="text-align: justify; border-left: 10px solid #0072BC !important;">
            <p class="lead">
                Salmobase is a tool for making molecular genomic resources for salmonid species publically available in a framework of visualizations and analytic tools.
            <br><br>
                Salmonids are ray-finned fishes which constitute 11 genera and at least 70 species including Atlantic salmon, whitefishes, graylings, rainbow trout, and char. 
                The common ancestor of all Salmonidae experienced a whole genome duplication (WGD) ~80 million years ago, resulting in an autotetraploid genome. 
                Genomic rediplodization is still going on in salmonid species, providing an unique system for studying evolutionary consequences of whole genome duplication. 
                In recent years, high quality genome sequences of Atlantic salmon and Rainbow trout has been established, due to their scientific and commercial values.
            </p>
        </div>

      <!-- Feedback -->
        <h1 id="Feedback" class="mb-1" style="font-family: 'Comfortaa', cursive;">Feedback</h1>
        <div class="border-start ps-3" style="text-align: justify; border-left: 10px solid #0072BC !important;">
            <p class="lead">
                We appreciate your feedback! Please report any issues with the site or suggest a new feature or dataset you would like to see here by 
                <a href = "mailto:incoming+elixir-nmbu-salmobase-21676123-issue-@incoming.gitlab.com">sending an e-mail</a> 
            </p>
        </div>
    </div>

    <!-- Twitter -->
    <div class="col-md-4">
      <a class="twitter-timeline" data-height="400" href="https://twitter.com/salmobase1?ref_src=twsrc%5Etfw">Tweets by salmobase1</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
    
  <!-- Features -->
  <div class="row col-md-10 mx-auto mb-5">
      <h1 class="mb-1" style="font-family: 'Comfortaa', cursive;">Features</h1>
      <div id="carouselCaptions" class="carousel slide carousel-dark border- border-2" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'salmobase/img/feature-gene-details.png' %}" class="d-block w-100" alt="gene-details">
              <div class="carousel-caption" style="background-color: rgba(255, 255, 255, 0.7);">
                <h5>Gene details</h5>
                <p>Shows gene annotation and structure. View and navigate between orthologs in the gene tree or synteny visualisation.</p>
                <a href="{% url 'genes:gene' 'ENSSSAG00000079420' %}?assembly=Ssal_v3.1">Example<i data-feather="chevron-right"></i></a>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'salmobase/img/feature-jbrowse.png' %}" class="d-block w-100" alt="jbrowse">
              <div class="carousel-caption"  style="background-color: rgba(255, 255, 255, 0.7);">
                <h5>Jbrowse2 genome browser</h5>
                <p>View gene annotations, orthologs, genome alignments as well as your own local track files (bigwig,bed,bam,gff,etc..).</p>
                {% comment %} <a href="{% url 'jbrowse:index' %}?assembly=ICSASG_v2&loc=NC_027315.1%3A47947545..47999816&tracks=GCF_000233375.1_ICSASG_v2_genomic_filtered.gff">Example<i data-feather="chevron-right"></i></a> {% endcomment %}
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'salmobase/img/feature-blast.png' %}" class="d-block w-100" alt="blast">
              <div class="carousel-caption"  style="background-color: rgba(255, 255, 255, 0.7);">
                <h5>BLAST search</h5>
                <p>Search for genomic, transcript or protein sequences within an assembly.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'salmobase/img/feature-synteny-blocks.png' %}" class="d-block w-100" alt="synteny-blocks">
              <div class="carousel-caption"  style="background-color: rgba(255, 255, 255, 0.7);">
                <h5>Synteny block overview</h5>
                <p>Overview of the duplicated regions, with LORe/AORe indication.</p>
                <a href="{% url 'genomes:overview' species='RainbowTrout' assembly='USDA_OmykA_1.1' %}#synteny-blocks">Example<i data-feather="chevron-right"></i></a>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
      </div>
  </div>


  <!-- Footer logos -->
  <div class="row justify-content-evenly align-items-center">
      <div class="col-3 p-4 mt-4">
              <a href="https://elixir.no/">
                  <img src="{% static 'salmobase/img/elixir-logo.png' %}" class="img-fluid" alt="elixir">
              </a>
      </div>
      <div class="col-3 py-auto">
              <a href="https://cigene.no/">
                  <img src="{% static 'salmobase/img/cigene-logo.png' %}" class="img-fluid" alt="cigene">        
              </a>    
      </div>
      <div class="col-3 p-4">
              <a href="https://www.nmbu.no/">
                  <img src="{% static 'salmobase/img/nmbu-logo.gif' %}" class="img-fluid" alt="nmbu">
              </a>
      </div>
  </div>
</div>
{% endblock content %}

salmobase/salmobase/templates/salmobase/resources.html
{% extends 'salmobase/base.html' %}

{% block content %}
<h1>Resources</h1>
<iframe src="http://localhost:80/static/" title='static' width='100%', height='600px'></iframe>
{% endblock%}

salmobase/salmobase/templates/salmobase/searchbar.html
<!-- Search bar -->
<form autocomplete="off" action="{% url 'genes:search' %}" method="GET">       
    <div class="input-group border-bottom">
        <span class="input-group-text bg-white border-0">
            <i class="bi-search"></i>
        </span>
        <input id="autocomplete-input" name="q" class="form-control bg-white border-0" type="search" placeholder="Search genes (gene name, id or description)" aria-label="Search genes">
        <!-- <input type="hidden" id="assembly-filter" name="assembly" hidden=true> -->
        <input type="hidden" id="annotation-filter" name="annotation" hidden=true>
        <!-- Search filter dropdown -->
        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
          <i class="bi bi-sliders"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end p-3" aria-labelledby="dropdownMenuClickableInside">
          <li><h6>Search filters</h6></li>
          <!-- Species -->
          <li>
            <label for="species-filter"><h6 class="dropdown-header">Species</h6></label>
            <select id="species-filter" class="form-select">
              <option selected value="">Any</option>
              {% for x,y in all_species.items %}
              <option value="{{x}}">{{y.name_text}}</option>
              {% endfor %}
            </select>
          </li>
          <!-- Assembly -->
          {{ all_annotated_assemblies|json_script:"all_annotated_assemblies" }}
          <li>
            <label for="assembly-filter"><h6 class="dropdown-header">Assembly</h6></label>
            <select id="assembly-filter" class="form-select" name="assembly"></select>
          </li>

          <!-- Annotation -->
          <li><h6 class="dropdown-header">Annotation source</h6></li>
          <li>
            <div class="btn-group pb-1" role="group" aria-label="Basic checkbox toggle button group">
              <input type="checkbox" class="btn-check annotation-select" id="annotation-ensembl" value="Ensembl" autocomplete="off">
              <label class="btn btn-outline-secondary" for="annotation-ensembl">Ensembl</label>
            
              <input type="checkbox" class="btn-check annotation-select" id="annotation-ncbi" value="NCBI" autocomplete="off">
              <label class="btn btn-outline-secondary" for="annotation-ncbi">NCBI</label>
            </div>
          </li>
        </ul>
    </div>
  </form>

<script>
  // update assembly filter options when species change
  const all_annotated_assemblies = JSON.parse(document.getElementById('all_annotated_assemblies').textContent);
  const primaryAssemblies = '{{all_primary_assemblies}}'.split(',');
  const spcFilterSelect = document.getElementById('species-filter');
  const asmFilterSelect = document.getElementById('assembly-filter');
  const annFilterSelect = document.getElementById('annotation-filter');
  
  spcFilterSelect.addEventListener('change', (event) => {
    const spc = event.target.value;
    let selectedAsm = '';
    asmFilterSelect.options.length = 0;
    if(spc == ''){
      selectedAsm='{{all_primary_assemblies}}';
      asmFilterSelect.options.add(new Option('Latest', value='{{all_primary_assemblies}}'));
      asmFilterSelect.options.add(new Option('Any', value=''));
    } else {
      all_annotated_assemblies[spc].forEach( asm => {
        if(primaryAssemblies.includes(asm)) selectedAsm=asm;
        asmFilterSelect.options.add(new Option(asm,value=asm));
      });  
    }
    asmFilterSelect.value = selectedAsm;
    asmFilterSelect.dispatchEvent(new Event('change'));
  });
  spcFilterSelect.dispatchEvent(new Event('change'));

  // update annotation filter when either of the options are (un)checked
  const annFilterOptions = document.getElementsByClassName("annotation-select")
  for(const x of annFilterOptions){
    x.addEventListener('change', (event) => {
      let annotation = [];
      for(const y of annFilterOptions){
        if (y.checked) {
          annotation.push(y.value);
        }
      }
      annFilterSelect.value = annotation.join(',');
    })
  }
</script>

salmobase/salmobase/templates/salmobase/tools.html
{% extends 'salmobase/base.html' %}
{% load static %}

{% block head %}
<link rel='stylesheet' type='text/css' href="{% static 'salmobase/css/tools.css' %}"></style>
{% endblock head %}

{% block content %}
<div class='content'>
    <h1>Tools</h1>
    <div class='tools'>
        <a href="{% url 'jbrowse:index' %}"> Jbrowse </a>
        <a href="{% url 'blast:input' %}"> BLAST search </a>
        <a href="https://salmobase.org/SalMotifDB/" target="_blank"> SalMotifDB </a>
    </div>
</div>
{% endblock content %}