salmobase/blast/urls.py
from django.urls import path
from . import views

app_name = 'blast'

urlpatterns = [
    path('input', views.input, name='input'),
    path('result', views.result, name='result'),
]

salmobase/genes/urls.py
from django.urls import path
from . import views

app_name = 'genes'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:gene_id>', views.gene, name='gene'),
    path('<str:species>/<str:gene_name>', views.geneByName, name='geneByName'),
    path('search', views.search, name='search'),
    path('orthogroup', views.orthogroup, name='orthogroup'),
    path('synteny', views.synteny, name='synteny'),
]

salmobase/jbrowse/urls.py
from django.urls import path
from . import views

app_name = 'jbrowse'

urlpatterns = [
    path('', views.index, name='index'),
    path('config.json', views.config_json),
]

salmobase/salmobase/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('genes/', include('genes.urls')),
    path('genomes/', include('genomes.urls')),
#    path('tools', views.tools, name='tools'),
    path('blast/', include('blast.urls')),
    path('jbrowse/', include('jbrowse.urls')),
#    path('resources/', views.resources, name= 'resources'),
    re_path('djga/', include('google_analytics.urls')),
    path('alignments/', include('alignments.urls')),
]

salmobase/blast/models.py
from django.db import models

# Create your models here.

salmobase/blast/views.py
import re
from django.shortcuts import render
from django.http import Http404
from Bio.Blast import NCBIXML
import subprocess 
import tempfile
from salmobase.species import nameToText, getSequenceSource, getAssemblyNames, nameToName, getAnnotations, getPrimaryAssembly, getAllSpecies, isValidSpeciesName
from django.conf import settings
import logging
from genes.models import Transcripts, Genes

# Get an instance of a logger
logger = logging.getLogger("django")





def input(request):
    context = {
        'blastDBlist' : {x.spc: {y.asm: [z for z in y.annotations] for y in x.assemblies.values()} for x in getAllSpecies().values()},
        'primaryAsm' : {spc: getPrimaryAssembly(spc) for spc in getAllSpecies()}
    }

    return render(request, 'blast/input.html', context)

def result(request):
    seq = request.GET.get('seq', '')
    species = request.GET.get('species', '')
    assembly = request.GET.get('assembly', '')
    dbType = request.GET.get('dbType', '')
    blastType = request.GET.get('blastType', '')


    # validate input
    if not blastType in ['blastn', 'blastp', 'blastx', 'tblastn']:
        raise Http404(f'"{blastType}" is not a valid blast searchType')
    if not isValidSpeciesName(species):
        raise Http404(f'"{species}" is not a valid species name')
    if not assembly in getAssemblyNames(species):
        raise Http404(f'"{assembly}" is not a valid assembly for {species}')
    # dbType can be e.g. dna or rna_NCBI, protein_Ensembl etc.
    if not (dbType == 'dna' or re.search("^(rna|protein)_[^_]+$",dbType) != None):
        raise Http404(f'"{dbType}" is not a valid dbType')

    species = nameToName(species) # make sure the case is correct

    # build the blastdb path
    db = f'{settings.DATAFILES_BASE_PATH}/genomes/{species}/{assembly}'
    if(dbType == 'dna'):
        src = getSequenceSource(species,assembly)
        db = db+f'/sequence_{src}/blastdb/dna/{species}_{assembly}_dna_blastdb'
        dbTypeText = 'Whole genome'
    else:
        (molType, annotation) = dbType.split('_')
        if not annotation in list(getAnnotations(species,assembly)):
            raise Http404(f'"{annotation}" is not a valid annotation for {species} ({assembly})')

        db = db+f'/annotations/{annotation}/blastdb/{molType}/' +\
                f'{species}_{assembly}_{annotation}_{molType}_blastdb'
        dbTypeText = {'rna':'Transcript','protein':'Protein'}[molType] +\
                     f' ({annotation})'

    
    evalue = '0.001'
    query = tempfile.NamedTemporaryFile(prefix='blastquery_', mode='w+t')
    query.writelines(seq)
    query.seek(0)
    out = tempfile.NamedTemporaryFile(prefix='blastresult_')

    cmd = [blastType, '-query', query.name, '-db', db, '-out', out.name, '-outfmt', '5', '-evalue', evalue]
    logger.debug("Running blast with query sequence:\n"+seq)
    logger.debug("Blast command:" + ' '.join(cmd))

    output = subprocess.run(cmd, capture_output=True)

    # TODO: catch errors from blast, e.g. if query sequence is invalid
    if( output.returncode != 0 ):
        logger.debug(f'Blast failed (returncode:{output.returncode}):\n{output.stderr}')
        raise Http404(f'Error occured when running blast!')

    result = NCBIXML.read(open(out.name))
    query.close()
    out.close()

    if(dbType != 'dna'):
        # For transcripts (or proteins)
        # get gene ID and description
        hit_seqs = [x.hit_def.split(' ')[0] for x in result.alignments]
        q = Transcripts.objects.filter(gff_id__in=hit_seqs, asm=assembly, ann=annotation)
        hit_genes = {tx.gff_id: tx.gene_id for tx in q}
        hit_transcripts = {tx.gff_id: tx.transcript_id for tx in q}
        unique_hit_genes = list(set(hit_genes.values()))
        q2 = Genes.objects.filter(gene_id__in=unique_hit_genes, asm=assembly, ann=annotation)
        gene_descriptions = {g.gene_id: g.description for g in q2}

    # For each hit, extract the values to display:
    hits = []
    for alignment in result.alignments:
        hit_seq_id = alignment.hit_def.split(' ')[0]
        for hsp in alignment.hsps:
            hit_stats={
                'score': hsp.score,
                'query_cov': f'{100*(hsp.query_end-hsp.query_start)/result.query_length:.0f}%',
                'e_value': f'{hsp.expect}',
                'perc_identity': f'{100*hsp.identities/hsp.align_length:.0f}%',
                'subject_length':alignment.length,
            }

            if(dbType != 'dna'): # transcripts/proteins
                hit_info={
                    'transcript_id': hit_transcripts[hit_seq_id],
                    'gene_id': hit_genes[hit_seq_id],
                    'description': gene_descriptions[hit_genes[hit_seq_id]],
                }
            else: # whole genome
                if (hsp.sbjct_start > hsp.sbjct_end): # reverse hit
                    hit_info={
                        'hit_locus': f'{hit_seq_id}:{hsp.sbjct_end}..{hsp.sbjct_start}',
                        'description': f'{hit_seq_id}:{hsp.sbjct_start}-{hsp.sbjct_end} (reverse)',
                    }
                else:
                    hit_info={
                        'hit_locus': f'{hit_seq_id}:{hsp.sbjct_start}..{hsp.sbjct_end}',
                        'description': f'{hit_seq_id}:{hsp.sbjct_start}-{hsp.sbjct_end}',
                    }

            hits.append({**hit_info,**hit_stats})



    context = {
        'blastType': blastType,
        'species': species,
        'assembly': assembly,
        'species_text': nameToText(species),
        'dbTypeText': dbTypeText,
        'nSubjects': len(result.alignments),
        'nHits': len(hits),
        'hits':  hits,
    }

    return render(request, 'blast/result.html', context)

salmobase/blast/templates/blast/input.html
{% extends 'salmobase/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="col-md-6 mx-auto p-4">
        <!-- Blast search form -->
        <h1 class="display-6 mb-3">BLAST search</h1>
        <form action="{% url 'blast:result' %}">

            <!-- Species select -->
            <div class="input-group p-0 mb-2">
                <label for="selectSpecies" class="input-group-text bg-light">Species</label>
                <select id="selectSpecies" name="species" class="form-select" aria-label="Select species">
                    <!-- <option value="All">All species</option> -->
                  </select>
            </div>

            <!-- Assembly select -->
            <div class="input-group p-0 mb-2">
                <label for="selectAssembly" class="input-group-text bg-light">Assembly</label>
                <select id="selectAssembly" name="assembly" class="form-select" aria-label="Select assembly">
                    <!-- <option value="All">All species</option> -->
                  </select>
            </div>
            
            <!-- Database type select -->
            <div class="input-group p-0 mb-2">
                <label for='dbType' class="input-group-text bg-light">Database</label>
                <select id="dbType" name="dbType" class="form-select" aria-label="Select database type">
                </select>
            </div>

            <!-- Query sequence -->
            <div class="form-floating p-0 mb-2">
                <textarea class="form-control" id='seq' name='seq' style="height: 200px; font-size:0.5em;"></textarea>
                <label for='seq'>Query sequence</label>
            </div>

            <div class="d-flex justify-content-between">
                <!-- Blast type -->
                <div class="form-check input-group p-0 mb-2">
                    <input class="btn-check" type="radio" name="blastType" id="blastn" value="blastn" autocomplete="off" checked>
                    <label class="btn btn-outline-primary rounded-start" for="blastn">blastn</label>

                    <input class="btn-check" type="radio" name="blastType" id="blastp" value="blastp" autocomplete="off">
                    <label class="btn btn-outline-primary" for="blastp">blastp</label>

                    <input class="btn-check" type="radio" name="blastType" id="blastx" value="blastx" autocomplete="off">
                    <label class="btn btn-outline-primary" for="blastx">blastx</label>

                    <input class="btn-check" type="radio" name="blastType" id="tblastn" value="tblastn" autocomplete="off">
                    <label class="btn btn-outline-primary" for="tblastn">tblastn</label>
                </div>

                <!-- Submit button -->
                <div class="p-0 mb-2">
                    <button type="submit" id="submit" class="btn btn-success" disabled=true>BLAST</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block scripts %}

{{ blastDBlist|json_script:"blastDBlist" }}
{{ primaryAsm|json_script:"primaryAsm" }}

<script>

    // available blast DBs and default assemblies
    const blastDBlist = JSON.parse(document.getElementById('blastDBlist').textContent)
    const primaryAsm = JSON.parse(document.getElementById('primaryAsm').textContent)

    // selectors
    const spcSelect = document.getElementById('selectSpecies');
    const asmSelect = document.getElementById('selectAssembly');
    const dbSelect = document.getElementById('dbType');
    
    let queryHasAA = false;
    let dbIsProtein = false;
    const blastTypeBtns = document.querySelectorAll('input[name="blastType"]')

    function updateBlastType(){
        // disable/enable blast type options based on db type and query type
        document.getElementById('blastn').disabled = dbIsProtein | queryHasAA;
        document.getElementById('blastp').disabled = !dbIsProtein;
        document.getElementById('blastx').disabled = (!dbIsProtein) | queryHasAA;
        document.getElementById('tblastn').disabled = dbIsProtein;

        // If the currently selected option is invalid then select the first valid option
        let selectBlastTypeValid = false
        let firstValidBlastType = ""
        for( const b of blastTypeBtns){
            if(b.checked & !b.disabled){
                selectBlastTypeValid = true;
            }
            if(!b.disabled & firstValidBlastType == ""){
                firstValidBlastType = b.value;
            }
        }
        if(!selectBlastTypeValid){
            document.getElementById(firstValidBlastType).checked=true;
        }
    };

 
    // Populate selectors
    Object.keys(blastDBlist).forEach(function(spc) {
        spcSelect.options.add(new Option(spc));
    });
    
    spcSelect.addEventListener('change', (event) => {
        const spc = event.target.value;
        asmSelect.options.length = 0;
        Object.keys(blastDBlist[spc]).forEach(function(asm) {
            asmSelect.options.add(new Option(asm));
        });
        // select default assembly
        asmSelect.value = primaryAsm[spc]
        asmSelect.dispatchEvent(new Event('change'));
    });

    asmSelect.addEventListener('change', (event) => {
        const asm = event.target.value;
        const spc = spcSelect.value

        const prevSelection = dbSelect.value;
        dbSelect.options.length = 0;
        dbSelect.options.add(new Option(`Whole genome`,`dna`));
        blastDBlist[spc][asm].forEach(function(ann) {
            dbSelect.options.add(new Option(`Transcripts (${ann})`,`rna_${ann}`));
            dbSelect.options.add(new Option(`Proteins (${ann})`,`protein_${ann}`));
        });
        
        // if previous selection is available then choose that
        for ( let i = 0, l = dbSelect.options.length; i < l; i++ ) {
            if ( dbSelect.options[i].value == prevSelection ) {
                dbSelect.value = prevSelection;
                break
            } else {
                dbSelect.dispatchEvent(new Event('change'));
            }
        }

    });

    dbSelect.addEventListener('change', (event) => {
        const dbSelected = event.target.value;
        dbIsProtein = dbSelected.startsWith("protein");
        updateBlastType();
    })


    // select default species
    spcSelect.value = Object.keys(blastDBlist)[0]
    spcSelect.dispatchEvent(new Event('change'));

    const queryText = document.getElementById('seq');
    const blastButton = document.getElementById('submit');

    queryText.addEventListener('input', (event) => {
        const text = event.target.value;
        // Check if there are nucleotide or amino acid sequences in the query
        // ignore header lines
        // TODO: validate that there is only one header line and that it is on top
        const noHeaders = text.replace(/^>.*$/gm,"").toUpperCase();
        const hasNuc = /[ACGT]/.test(noHeaders);
        const hasAA = /[DEFHIKLMPQRSVWY]/.test(noHeaders);

        // if no sequence then don't allow submit
        blastButton.disabled = !(hasAA | hasNuc)

        // assume that query is protein so update valid blast type options
        if(queryHasAA != hasAA){
            queryHasAA = hasAA;
            updateBlastType()
        }
    });

</script>
{% endblock %}

salmobase/blast/templates/blast/result.html
{% extends 'salmobase/base.html' %}
{% load static %}
{% load replace %}

{% block head %}
{% endblock head %}

{% block content %}
<div class='container-flex p-4'>
    <div class="text-center">
        <span class="align-middle">{{blastType}} found </span>
        <span class="badge rounded-pill bg-success">{{nHits}}</span>
        <span class="align-middle"> hits across </span>
        <span class="badge rounded-pill bg-primary">{{nSubjects}}</span>
        <span class="align-middle"> subjects in the {{species_text}} ({{assembly}}) {{dbTypeText}} database</span>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                {% if dbTypeText != "Whole genome" %}
                <th scole="col">transcript ID</th>
                <th scole="col">gene ID</th>
                <th scole="col">description</th>
                {% else %}
                <th scole="col">hit location</th>
                {% endif %}
                <th scope="col">score</th>
                <th scope="col">query coverage</th>
                <th scope="col">e-value</th>
                <th scope="col">identity</th>
                <th scope="col">subject length</th>
                <!-- <th scope="col" style="width: 100px;">match</th> -->
            </tr>
        </thead>
        <tbody>
            {% for hit in hits %}
                {% if dbTypeText != "Whole genome" %}
            <tr data-href="{% url 'genes:gene' hit.gene_id %}?assembly={{assembly}}">
                <td>{{hit.transcript_id}}</td>
                <td>{{hit.gene_id}}</td>
                <td>{{hit.description}}</td>
                {% else %}
            <tr data-href="{% url 'jbrowse:index' %}?assembly={{assembly}}&loc={{hit.hit_locus}}">
                <td>{{hit.description}}</td>
                {% endif %}
                <td>{{hit.score}}</td>
                <td>{{hit.query_cov}}</td>
                <td>{{hit.e_value}}</td>
                <td>{{hit.perc_identity}}</td>
                <td>{{hit.subject_length}}</td>

            <tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block scripts %}
<script>
//  Make table rows clickable
    $(function(){
        $('.table tr[data-href]').each(function(){
            $(this).css('cursor','pointer').hover(
                function(){ 
                    $(this).addClass('active'); 
                },  
                function(){ 
                    $(this).removeClass('active'); 
                }).click( function(){ 
                    document.location = $(this).attr('data-href'); 
                }
            );
        });
    });
</script>
{% endblock scripts %}